# 음식종류별로 즐겨찾기수가 가장 많은 식당의 음식 종류, ID, 식당 이름, 즐겨찾기수를 조회
# 음식 종류를 기준으로 내림차순 정렬

# SELECT
#     FOOD_TYPE,
#     REST_ID,
#     REST_NAME,
#     FAVORITES
# FROM REST_INFO

# GROUP BY FOOD_TYPE
# # HAVING FAVORITES = MAX(FAVORITES)
# ORDER BY FOOD_TYPE DESC

# 음식 종류 기준으로 내림차순 정렬

# SELECT
#     FOOD_TYPE,
#     REST_ID,
#     REST_NAME,
#     FAVORITES
# FROM REST_INFO
# ORDER BY FAVORITES DESC

## 즐겨찾기가 가장 많은 식당 순으로 정렬
# SELECT
#     FOOD_TYPE,
#     REST_ID,
#     REST_NAME,
#     FAVORITES
# FROM REST_INFO
# ORDER BY FOOD_TYPE DESC, FAVORITES DESC


SELECT
    RI.FOOD_TYPE,
    RI.REST_ID,
    RI.REST_NAME,
    RI.FAVORITES
FROM REST_INFO RI
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) MF
ON RI.FOOD_TYPE = MF.FOOD_TYPE
AND RI.FAVORITES = MF.MAX_FAV
ORDER BY RI.FOOD_TYPE DESC;
