SELECT
    ANIMAL_ID,
    ANIMAL_TYPE,
    NAME
FROM ANIMAL_INS AS AI
JOIN ANIMAL_OUTS AS AO
USING (ANIMAL_ID, ANIMAL_TYPE, NAME)
WHERE SEX_UPON_INTAKE LIKE "%In%"
AND (SEX_UPON_OUTCOME LIKE "%Ne%"
OR SEX_UPON_OUTCOME LIKE "%Sp%")
ORDER BY ANIMAL_ID