# 2021년에 가입한 전체 회원 중
# 상품을 구매한 회원수와 상품을 구매한 회원의 비율(=2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수)
# 년, 월 별로 출력 // 년, 월 오름차순
# 상품을 구매한 회원의 비율은 소수점 두번째자리에서 반올림

#2021년에 회원 가입한 고객의 상품 판매 정보
WITH CI AS (
SELECT 
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    USER_ID,
    PRODUCT_ID
    # (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021) AS TOTAL,
    # ROUND(COUNT(USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO    
FROM ONLINE_SALE
WHERE USER_ID IN 
    (SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021)
ORDER BY USER_ID, 1,2
)

SELECT 
    YEAR,
    MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM CI
GROUP BY YEAR,MONTH
ORDER BY 1,2