# SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 

# 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서
# 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 
# 대여 기록 ID와 대여 금액 리스트를 출력
# 대여 금액을 기준으로 내림차순, 대여 기록 ID를 기준으로 내림차순


WITH TMP AS (
SELECT
    HISTORY_ID, 
    CAR_TYPE,
    DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) AS TOTAL_FEE,
    DATEDIFF(END_DATE, START_DATE) + 1 AS RENT_DAYS,
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN "90일 이상"
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN "30일 이상"
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN "7일 이상"
        ELSE NULL
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
JOIN CAR_RENTAL_COMPANY_CAR 
USING (CAR_ID)
WHERE CAR_TYPE = '트럭'
)

SELECT
    HISTORY_ID,
    CASE
        WHEN DURATION_TYPE IS NULL THEN TOTAL_FEE
        ELSE TOTAL_FEE - ROUND((TOTAL_FEE * DISCOUNT_RATE / 100),0)
    END AS FEE
FROM TMP
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CP
USING (CAR_TYPE, DURATION_TYPE)
ORDER BY FEE DESC, HISTORY_ID DESC