# 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
# 회원 이름, 리뷰 텍스트, 리뷰 작성일
# 리뷰 작성일을 기준으로 오름차순, 리뷰 작성일이 같다면 리뷰 텍스트를 기준으로 오름차순

WITH RV AS (
SELECT 
    COUNT(*) AS REVIEW_CNT,
    MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
)

SELECT
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d")
FROM MEMBER_PROFILE 
JOIN REST_REVIEW
USING (MEMBER_ID)
JOIN RV
USING (MEMBER_ID)
WHERE REVIEW_CNT = (SELECT MAX(REVIEW_CNT) FROM RV)
ORDER BY REVIEW_DATE, REVIEW_TEXT



# SELECT 
#     COUNT(*) AS REVIEW_CNT,
#     MEMBER_ID,
#     MEMBER_NAME
# FROM REST_REVIEW
# JOIN MEMBER_PROFILE
# USING (MEMBER_ID)
# GROUP BY MEMBER_ID, MEMBER_NAME
# ORDER BY REVIEW_CNT DESC


