## 부모 형질을 모두 보유한 대장균 table INNER join
# SELECT ED.ID, ED.GENOTYPE, EDC.PARENT_GENOTYPE, (ED.GENOTYPE & EDC.PARENT_GENOTYPE) AS BITMASK
# FROM ECOLI_DATA AS ED
# INNER JOIN (SELECT ID, GENOTYPE AS PARENT_GENOTYPE FROM ECOLI_DATA) AS EDC ON ED.PARENT_ID = EDC.ID
# WHERE ED.GENOTYPE & EDC.PARENT_GENOTYPE = EDC.PARENT_GENOTYPE 
# # ORDER BY ID ASC

SELECT ED.ID, ED.GENOTYPE, EDC.PARENT_GENOTYPE
FROM ECOLI_DATA AS ED
INNER JOIN (SELECT ID, GENOTYPE AS PARENT_GENOTYPE FROM ECOLI_DATA) AS EDC ON ED.PARENT_ID = EDC.ID
WHERE ED.GENOTYPE & EDC.PARENT_GENOTYPE = EDC.PARENT_GENOTYPE 
ORDER BY ID ASC