# 대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차
# 해당 기간 동안의 월별 자동차 ID 별 총 대여 횟수
# 월을 기준으로 오름차순 정렬
# 월이 같다면 자동차 ID를 기준으로 내림차순 정렬
# 특정 월의 총 대여 횟수가 0인 경우에는 결과에서 제외


# 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상
# SELECT
#     CAR_ID,
#     COUNT(CAR_ID) AS CNT
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
# GROUP BY CAR_ID
# HAVING CNT >= 5
# ORDER BY CNT 

# SELECT
#     MONTH(START_DATE) AS MONTH,
#     t1.CAR_ID,
#     COUNT(t1.CAR_ID) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS t1
# JOIN (
#     SELECT
#         CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
#     GROUP BY CAR_ID
#     HAVING COUNT(CAR_ID) >= 5
# ) AS t2
# ON t1.CAR_ID = t2.CAR_ID
# WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
# GROUP BY t1.CAR_ID, MONTH(START_DATE)
# ORDER BY MONTH, CAR_ID DESC


# 챗지피티 모범답안
WITH FrequentlyRentedCars AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
JOIN FrequentlyRentedCars
    ON CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID = FrequentlyRentedCars.CAR_ID
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(START_DATE), CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
ORDER BY MONTH, CAR_ID DESC;
