## 풀이 1. 틀림. TRUE/FALSE 반환이 아니라 1/NULL로 명시하기
## 일부 DBMS에서는 FALSE
SELECT 
    SUM(CASE
            WHEN n.FISH_NAME = 'BASS' THEN 1
            WHEN n.FISH_NAME = 'SNAPPER' THEN 1
            ELSE 0
        END)AS FISH_COUNT
FROM FISH_INFO AS f
JOIN FISH_NAME_INFO AS n ON f.FISH_TYPE = n.FISH_TYPE


## 풀이2. 정답
# SELECT
#     COUNT(*) AS FISH_COUNT
# FROM FISH_INFO AS f
# JOIN FISH_NAME_INFO AS n ON f.FISH_TYPE = n.FISH_TYPE
# WHERE n.FISH_NAME IN ('BASS', 'SNAPPER')