SELECT
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES AS bs
JOIN BOOK AS b
    ON b.BOOK_ID = bs.BOOK_ID
WHERE
    YEAR(SALES_DATE) = 2022
    AND MONTH(SALES_DATE) = 1
GROUP BY CATEGORY
ORDER BY CATEGORY